### ISSUE TITLE
25 Apr - (General) - User Authentication - Front-end connection with endpoints

### ISSUE THREAD

**Issue by emiliogonmar2002** [13th-office/IBM-SkillBoard#20]
Connect endpoint for User Auth with front-end

**Comment by gonzalpi** [comment]
Back end authentication implemented. On login cookie `_session_id` is set and is NOT accessible using JavaScript. All requests to other endpoints should include it (e.g. `fetch("127.0.0.1:3000/api/v1/users", { credentials: "include" })` or `axios.get("127.0.0.1:3000/api/v1/users", { withCredentials: true })`)
