### ISSUE TITLE
21 Apr - (Back-end) Get Certifications Endpoint

### ISSUE THREAD

**Issue by emiliogonmar2002** [13th-office/IBM-SkillBoard#37]
- Create endpoint that receives **session token**
- The endpoint should return a list of certificates with each ceritificates information in JSON Format:

[
    {name: "Azure DevOps Certificate", date: "14-May-2099", ...},
    {name: "Amazon AWS DevOps Certificate", date: "14-May-2099", ...},
    ...
]

**Comment by gonzalpi** [comment]
Not implementing access control yet, to be fixed in #53
