### ISSUE TITLE
(Endpoint) - Get Dashboard Certifications

### ISSUE THREAD

**Issue by emiliogonmar2002** [13th-office/IBM-SkillBoard#95]
This endpoint returns all certifications from the DB, depending the type of the Certificate

The route should be dynamic and have the type for certificate:
    - **All**: Returns all certificates, no matter the type
    - **Industry**: Returns all certificates with Industry Type
    - **IBM**: Returns all certificates with IBM type
    - **My Team**: Returns all certificates of My Team (this is not a type in the database, should require more logic)

#### Response body
Array of certificates with their category included
```
[
    {
      id: "1",
      name: "SCRUM Master Certificate",
      type: "IBM",
      categories: [
        { id: "1", name: "SCRUM" },
        { id: "2", name: "Organization" },
      ],
      expiration_date: "Feb 14th, 2099",
    },
    ...
]
```

**Comment by gonzalpi** [comment]
@emiliogonmar2002 este issue ya está en el #83, copiaré y pegaré la info allá
